### ISSUE TITLE
How to move waydroid internal storage wherever i want?

### ISSUE THREAD

**Issue by EliasGabr** [waydroid/waydroid#1208]
Sorry to bother, but I just wanted to ask how to use another drive or something for the storage of waydroid (like in qemu), because i dont have any disk space left on my / drive

thanks in advance!

**Comment by psychon-night** [comment]
Use a symlink, that's what i'm doing and it's worked so far.

Disclaimer: you *might* need to reinstall Waydroid for this to work. I had to... but it's worth a shot

STOP Waydroid completely:
`sudo systemctl stop waydroid-container`

Waydroid's path is `/home/<username/.local/share/waydroid`
Move that folder to your desired drive. In my setup, that's `/media/ext/`, so I'll use that as an example. That means my new Waydroid path is `/media/ext/waydroid`

From here it's fairly easy, just create a symlink. `sudo ln -s /media/ext/waydroid /home/<username>/.local/share`
Restart Waydroid: `sudo systemctl start waydroid-container`

Now, wait ~30 seconds to give it a chance to get ready. Then you can run `waydroid show-full-ui` (NO sudo here) and see what happens

**Comment by Megalomaniak** [comment]
> Use a symlink, that's what i'm doing and it's worked so far.
> 

Can confirm: that works.

**Comment by mamalubitlal** [comment]
is it gonna increase storage space in waydroid?

**Comment by JL2210** [comment]
Is there a config to change this without a symlink? I do `find ~` quite often and get permission errors on everything.

**Comment by psychon-night** [comment]
> is it gonna increase storage space in waydroid?

Entirely depends on your setup. If you move Waydroid to a disk with more space, yes

**Comment by psychon-night** [comment]
> Is there a config to change this without a symlink? I do `find ~` quite often and get permission errors on everything.

Not from what I've seen, no
If you want `find` to work correctly, I recommend doing a `chmod u+r <Waydroid folder> --recursive`

**Comment by CanuckGod** [comment]
Had an issue once before where everything didn't move correctly and had to reinstall everything, but I've since found that that if you issued the copy command as such when transferring over your files:
`sudo cp -a /home/[USERDIR]/.local/share/waydroid /home/  /[your new location]`
This way, the permissions would seem to transfer correctly without issue - the -a flag 'archives' everything about the files (and includes recursive directory copy), which in my case of using Fedora, also doesn't break SELinux attributes.
After that, it's just a simple step of linking the directories:
`ln -s /[your new location] /home/<USERDIR>/.local/share/waydroid`
As above in psychon's post, you'll want to stop the Waydroid service completely before executing any file commands and then restart when finished.
