### ISSUE TITLE
[BUG] Waydroid stuck at login screen.

### ISSUE THREAD

**Issue by orcbolg3612** [waydroid/waydroid#1235]
[###] Describe the bug

I am using fedora 39 and my waydroid stuck at login screen. This shitty screen always appear even i close waydroid and waydroid reopen itself. Before, i install allthings from things from waydroid-script on github. My waydroid version that i am using is GAPPS.
![image](https://github.com/waydroid/waydroid/assets/154581201/6bdb863e-6e92-4221-b98a-c1f31d6e4893)

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Fedora 39 with latest update

### Kernel version

6.6.9-200.fc39.x86_64

### Desktop Environment

GNOME 45

### GPU

AMD Ryzen 5000 series. 

### Logs

Log too long to copy in terminal.

**Comment by Zaenalabidin57** [comment]
are you installing hack nodataperm? i got the same issue when installing those, just  `sudo python3 main.py remove nodataperm` and restart the waydroid, i hope it solved your problem

**Comment by AndrewPrzelucki** [comment]
For anyone having this issue after an update, because I was also stuck on the boot logo (first time this happened). Clean install didn't help. I'm running waydroid on Kubuntu in an X session, through Weston. My solution right now is to start the waydroid session not with "waydroid session start" and "waydroid show-full-ui" but only with "WAYLAND_DISPLAY=/run/user/1000/wayland-1 waydroid first-launch". I successfully reinstalled waydroid with Gapps. I didn't do anything to address the issue with binder or anything else.
