### ISSUE TITLE
[BUG] Failed to load binder driver

### ISSUE THREAD

**Issue by hhhhhge** [waydroid/waydroid#1326]
### Describe the bug

when i run 'sudo waydroid init'

### Waydroid version

1.4.2

### Device

Linux Smartphone

### Operating System

Ubuntu 22.04 arm64

### Kernel version

6.1.43-rockchip-rk3588

### Desktop Environment

GNOME 42.9

### GPU

mali

### Logs

[15:22:05] Failed to load binder driver
[15:22:05] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/6.1.43-rockchip-rk3588
[15:22:05] ERROR: Binder node "binder" for waydroid not found
[15:22:05] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.

**Comment by hhhhhge** [comment]
[dmesg.txt](https://github.com/waydroid/waydroid/files/14622827/dmesg.txt)
[logcat.txt](https://github.com/waydroid/waydroid/files/14622828/logcat.txt)
[waydroid.log](https://github.com/waydroid/waydroid/files/14622829/waydroid.log)

**Comment by Devil64-Dev** [comment]
I guess is not a Waydroid issue, since the log say: `binder_linux not found` in the modules directory, that means the module is not installed for your current kernel version, so you may have to upgrade the kernel and then reboot or if the kernel doesn't provide the module you must compile the module and install it by yourself.

Generally the default kernel provided by distributions are compiled with the android `binder` module disabled, so you have to use other kernel which has it enabled by default like the `zen-kernel` or `xanmod kernel`. Or you can get the sources of your current kernel, enable the `binder_linux` module, compile and install (this requires a bit knowledge on Linux kernel building).

The most easy way to get it working is just by compiling the module and installing it.

**Useful links**
Anbox modules: <https://github.com/choff/anbox-modules>

**Comment by lidgnulinux** [comment]
It's on kernel's device and not waydroid. SMH.

**Comment by chenxy-china** [comment]
你好，你在PC上的ubuntu22.04上试过 waydrid能正常运行吗，我一直运行失败
