### ISSUE TITLE
Sigo con inconvenientes en apps que rotan la pantalla

### ISSUE THREAD

**Issue by Theo3113** [waydroid/waydroid#201]
Como lo dije sin más. Tengo una mini laptop, y en aplicaciones como Facebook Lite o Whatsapp la pantalla gira a mi izquierda, el cursor se usa en forma errática y confusa debido a la posición en la que queda el sistema de LineajeOs, y la flecha solamente llega hasta la mitad de la pantalla y no deja avanzar hasta los menús de retroceso y ventanas abiertas de Android. En Lite directamente me sucede apenas y abro la aplicación, y en Whatsapp cuando se realiza una llamada.

**Comment by pizdjuk** [comment]
I'm pretty sure it is because screen rotation in the waydroid dont correspond to the rotation in the contatiner. I mean we need the coordinates recalculation which obviously dont occure.

I suffered the same bug, a workaround is to resize the screen within you start waydroid to be more height then width :)
So no screen rotation will occure.
