### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by PengXiao03** [waydroid/waydroid#216]
E: The repository 'https://repo.waydro.id focal Release' does not have a Release file.

I don't quite understand this aspect. It gave me this error, what should I do?

**Comment by gotlougit** [comment]
Run the following command, ```sudo apt install ca-certificates```

Right now, apt doesn't think the connection to waydroid repository is secure since it doesn't have the certificates, that's why you're most likely facing this problem. 

This should actually be written in the official waydroid docs as well.

**Comment by Matimatou** [comment]
This command has been added in the doc but does not fix the issue. 
I'm using Pop OS 22.04 codename of the distro : jammy.
Is there a way to fix the issue ?

**Comment by cniw** [comment]
> This command has been added in the doc but does not fix the issue.
> I'm using Pop OS 22.04 codename of the distro : jammy.

Yeah of course that command won't fix that issue because waydroid repo currently not yet provided packages repo for jammy

> Is there a way to fix the issue ?

I have 2 automated scripts to get waydroid on debian based distro and you can use it to install waydroid on your distro if you want
https://gist.github.com/cniw/7a0220ce8b75368f7f57aa422d3fea97
https://gist.github.com/cniw/98e204d7dbc73a3fa1bf61629b2a2fc1
