### ISSUE TITLE
Problème waydroid

### ISSUE THREAD

**Issue by Biiby** [waydroid/waydroid#219]
Bonjours, j'essaie d'installer waydroid sur ubuntu 20.04 focal fossa, mais a la fin de ligne de code il me répond toujours :" E: Impossible de trouver le paquet waydroid" avez vous une solution ?
Merci

**Comment by gotlougit** [comment]
Have you added the waydroid repository as the official installation instructions specify?
If you have, ensure that ```ca-certificates``` is also installed since without it, apt won't think that the connection to the waydroid repos is secure as it doesn't have the certificates.

Try running the following command: ```sudo apt install ca-certificates``` and then try installing waydroid

**Comment by aleasto** [comment]
Missing info. Should work if you just follow the instructions
