### ISSUE TITLE
[QUESTION] Is there a way to run waydroid on a headless server?

### ISSUE THREAD

**Issue by vadd98** [waydroid/waydroid#230]
I need to run an android app on multiple headless ubuntu servers.
At the moment I'm using a docker container with a qemu emulation of android (Redroid image container), but I'd prefer to use waydroid for performance.
Is there a way to do it, like a fake wayland display or similar?

**Comment by fabiomaia** [comment]
There is this piece of "documentation" in the Telegram group

> In order to get Waydroid to work through a VM, you may need to adjust a couple things in waydroid_base.prop. 
> 
> Change both these to what is shown below: 
> ro.hardware.gralloc=default
> ro.hardware.egl=swiftshader
> 
> Restart the container afterwards

I have not tried it myself nor am I sure it's relevant. Curious if you find a working solution though!

**Comment by 530f6caa** [comment]
You might find the [weston-rdb](https://manpages.ubuntu.com/manpages/focal/en/man7/weston-rdp.7.html) backend useful for this. I'm not sure what performance is like.

**Comment by aleasto** [comment]
Yes, you need a headless Wayland compositor then some way to forward the video output to you.
Some options may be `kwin_wayland --virtual`, `mutter --wayland --headless`, `WLR_BACKENDS=headless sway` and so on...

**Comment by dialmond** [comment]
I know this issue is complete, but I'm still having some trouble with this if anyone has any insight?

So my goal is to have waydroid running on a headless server somewhere, and I'll ssh into it whenever I need to, and forward the video output. Ideally I could set my server up in such a way that I don't have to install anything special on the client (so I can access my emulated waydroid device from as many computers as possible).

So far I got [waypipe](https://www.mankier.com/1/waypipe) working, where I do something like `waypipe ssh <my_server> sway`. This forwards the sway desktop environment to me, and from there I open up a terminal on it and run `waydroid show-full-ui`. Great! I also modified my `sway` config file to auto-start `waydroid` on launch, so it's even more smooth for me.

Only problem with `waypipe` is that to my knowledge, it must be installed on the client as well, and the client must be running Wayland. Ideally I could just set this up to work with just X11 forwarding.

I installed `weston` on my server (inspired by [this issue](https://github.com/waydroid/waydroid/issues/195#issuecomment-953926526)), and can now do `ssh -Y <my_server> weston` from most machines now. This successfully forwards the `weston` window to my client, but now when I run `waydroid show-full-ui` I get `waiting for binder Service Manager`.

I'll keep on doing some research and edit this if I find a solution, but would anyone have any advice on how to proceed? Thanks!

**Comment by realyukii** [comment]
so you ended up using waydroid + weston on the server, would you like to share your story, how about the experience? is it smooth? what's the spec of your server? is it possible to run waydroid without GPU attached?

**Comment by 0xcad** [comment]
> @realyukii:  so you ended up using waydroid + weston on the server, would you like to share your story, how about the experience? is it smooth? what's the spec of your server? is it possible to run waydroid without GPU attached?

So when I made my comment originally I needed a way to run 2FA for school, but at the time I was using a flip phone and I didn't want to pay for a yubikey. I got a VPS  from a university club (server specs included below) then put the 2FA app Duo on it using waydroid. Whenever I needed a 2FA code and had my laptop on me I used `waypipe`, and whenever I was out, say, using a public library computer or something, I used X11 forwarding and `weston`. This sounds really insecure and hacky, probably because it was, but at least I had a strong password + server monitoring.

It was quite laggy,  I had no GPU, but it totally got the job done. It would take maybe 30 secs-1 min for the android to load up. The screen had a pretty low/choppy frame rate, but again I was only on the server for long enough to get my 2FA code, which I needed maybe 2-3 times a month. I restarted the waydroid device each time, but noticed that if it was running for longer it seemed to perform better in terms of fps/loading time?

Sometimes I'd get these "System UI is not responding" type messages, and I just ignored them and kept going and usually things would work, just slowly. Other times it refreshed the screen and took a bit longer to reload. Couldn't recommend this for regular use but YMMV.

If for some reason this fits whatever cursed 2FA needs you may have (my school required Duo), this definitely worked well for me, but maybe next time I'll just splurge on a yubikey or something. Generically, if you need waydroid infrequently this is fine, but if you spend a lot of time on it you'll probably be frustrated.

Server specs:
```
~$ lscpu
...
Model name:            Intel(R) Xeon(R) CPU           X5690  @ 3.47G
```

Ram: 3.8Gi total, but I don't think this was the bottleneck.
