### ISSUE TITLE
About New Google Play policy

### ISSUE THREAD

**Issue by dtantono** [waydroid/waydroid#253]
Hi
Since AAB will replace apk in Android for long term. is AAB file will be supported as well?

**Comment by electrikjesus** [comment]
If AOSP supports it, then you can assume we will also.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@electrikjesus, and are we to assume the opposite if AOSP does not support it?

**Comment by electrikjesus** [comment]
If I could predict the future, I wouldn't be a programmer

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@electrikjesus, I merely mean that because I believe that AOSP does not support it currently, and that the developers of it do not intend to, should we expect that support for it shall not be added by the developers of WayDroid? I assume that they want to keep their build as close to AOSP as is possible.
