### ISSUE TITLE
Waydroid is too strict in how the script is handled

### ISSUE THREAD

**Issue by Quackdoc** [waydroid/waydroid#263]
here are some of the thing that waydroid does that should be optional, or otherwise done in a different way

1. mounts the entire /dev/dri folder. ideally it should just be a single gpu. as this can lead to some graphics issues that are not solved by simply specifying gbm.gralloc
2. mount all the /dev/video device, this is a rather significant privacy concern for people who are looking at waydroid as a way to increase privacy
3. networking is not only quite strict with it's environment, having the network bridge created and destroyed means that it may break some peoples custom routing and firewall setups. while it is nice to have, I think the option to instead have a permanent bridge would be better in these scenarios, and not to mention, a wack to easier to diagnose. 

these are a few of the issues off the top of my head. I'm not sure the best way to fix these issues. but in my opinion they are issues that ought to be addressed. while having everything set is convient, I think a user prompt for configuration is probably better. 

EDIT: I think for networking at least, a simple temporary fix would be to check for waydroid0 if it already exists, then just exit the script

**Comment by v1nsai** [comment]
Can confirm that replacing my /usr/lib/waydroid/data/scripts/waydroid-net.sh with PR #267 fixed this issue for me, nice one @Quackdoc!  I've been banging my head on solutions that seem to work for everyone else but never for me, I think the issue was as you mentioned, a conflict with anbox.  I tried anbox before waydroid and I don't think I bothered uninstalling it so that would make sense.

**Comment by Quackdoc** [comment]
this was fixed long ago
