### ISSUE TITLE
binder module not found

### ISSUE THREAD

**Issue by raffaem** [waydroid/waydroid#30]
I have Fedora 34 Workstation with a self-built 5.14 kernel that includes ashmem and binder.

waydroid seems unable to find binder:
```
$ sudo python3 waydroid.py init
[20:19:00] Failed to load binder driver for devices: anbox-vndbinder,anbox-hwbinder
[20:19:00] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.14.0
[20:19:00] ERROR: Binder node "vndbinder" for waydroid not found
[20:19:00] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.
```

**Comment by LecrisUT** [comment]
Can you go into details on how you enabled `ashmem` and `binder` on your Fedora setup? How did you test for the modules presence?

My guess for this issue is that waydroid only checks for `dkms` loaded modules, but not for built-in from compiled kernels. I am trying building it myself on my Fedora desktop using [`Frogging-Family/linux-tkg`](https://github.com/Frogging-Family/linux-tkg), and I'll start testing waydroid once I get that running. Note for anyone trying this as well, `linux-tkg` may brick all other kernels as well, so follow Frogging-Family/linux-tkg#303 on how that is resolved.

**Comment by anoraktrend** [comment]
have an issue with "binder node" binder not being found using Droidian on sargo (Google Pixel 3A)

**Comment by raffaem** [comment]
> Can you go into details on how you enabled `ashmem` and `binder` on your Fedora setup? How did you test for the modules presence?

From the kernel build options:

![image](https://user-images.githubusercontent.com/54762742/132316947-13693949-4a94-4381-875b-6ca90a12ac95.png)

**Comment by LecrisUT** [comment]
> From the kernel build options:

You have lost me there. What gui application you used to build the kernel?

**Comment by raffaem** [comment]
> > From the kernel build options:
> 
> You have lost me there. What gui application you used to build the kernel?

`make xconfig`

**Comment by Djhg2000** [comment]
Can confirm on Debian Sid with kernel 5.14.2 :

```
# grep -i binder /boot/config-5.14.2 
CONFIG_ANDROID_BINDER_IPC=y
CONFIG_ANDROID_BINDERFS=y
CONFIG_ANDROID_BINDER_DEVICES="binder,hwbinder,vndbinder"
# CONFIG_ANDROID_BINDER_IPC_SELFTEST is not set
```

I get a very subtle difference in the error message though, in my case it fails at `binder` instead of `vndbinder`. Not sure if it's significant but I figure it's worth mentioning. Full output:

```
# waydroid init
[05:21:34] Failed to load binder driver for devices: anbox-binder,anbox-vndbinder,anbox-hwbinder
[05:21:34] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.14.2
[05:21:34] ERROR: Binder node "binder" for waydroid not found
[05:21:34] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.
```

I hope I'm not cluttering the thread with these code blocks.

**Comment by LecrisUT** [comment]
It might be worth noting that the `binder` and `ashmem` installed from kernel compilation are not detected via `modprobe`, or maybe a different name is needed. Also the `binder` is installed slightly differently with `/dev/binderfs` instead of `/dev/binder`. We will have to play around with the configurations, maybe bypass the checks and see if it can `waydroid init` eitherway. If someone knows how to test `binder` and `ashmem` independent of `waydroid` or  `anbox`, that would be useful for amateurs like me.

**Comment by erfanoabdi** [comment]
https://github.com/waydroid/waydroid/commit/4434f1120459fb65ffd5b48280c6ec10046b633d this helps

**Comment by Djhg2000** [comment]
@erfanoabdi Thank you, that commit fixes this issue on my system.

**Comment by raffaem** [comment]
@erfanoabdi thank you that moves the initialization forward.

I'm closing this since I don't get this error message anymore

**Comment by Doomsdayrs** [comment]
On Ubuntu Impish Indri, This problem still persists for me.

Running on 5.13.0-14-generic kernel.

**Comment by erfanoabdi** [comment]
@Doomsdayrs use lowlatency kernel, not generic

**Comment by Doomsdayrs** [comment]
@erfanoabdi I moved my issue to #47 

lowlatency kernel does not work either

**Comment by youling257** [comment]
ubuntu kernel, 5.15.0-13-generic，CONFIG_ANDROID=y
CONFIG_ANDROID_BINDER_IPC=m
CONFIG_ANDROID_BINDERFS=m
CONFIG_ANDROID_BINDER_DEVICES=""
# CONFIG_ANDROID_BINDER_IPC_SELFTEST is not set

have to rebuild kernel by myself.

**Comment by Armwillking** [comment]
In my debian11 replaced the 5.4 version of the Linux kernel, and successfully installed anbox binder and ashmem kernel modules in https://github.com/anbox/anbox-modules. I also compiled and installed libglibutil, libgbinder, gbinder-Python and Waydroid in Waydroid. Binder node "vndbinder" for Waydroid not found" ERROR: Binder node "vndbinder" for Waydroid not found" I don't know why waydroid must use the "vndbinder" device node? How is it different from a "Binder" device node? How do I add the "vndbinder" device node to the current 5.4 kernel version? Then you can use Waydroid normally. Thank you very much!
