### ISSUE TITLE
Install of Kobo APK failed - NativeHelper: Failure copying native libraries [errorCode=-113]

### ISSUE THREAD

**Issue by nachfuellbar** [waydroid/waydroid#355]
**Describe the bug**
Install of Kobo APK failed

**General information:**
 - Waydroid tools Version 1.2.0
 - Waydroid Images Version GAPPS 20220316

**Desktop:**
 - OS: Arch Linux
 - GPU: RX Vega 7 (Ryzen 7 4700U)
 - Kernel version: 5.17.1-zen1-1-zen
 - Host mesa version: 22.0.1-3
 - Desktop: GNOME 42.0-1

**Logs **
 - https://gist.github.com/nachfuellbar/1b8cc8d0a675b333a2bc7b1bfe57cb1f
 - https://gist.github.com/nachfuellbar/e3deb07a8b50ced92f207b4c124e9553

**Comment by cniw** [comment]
> Failed to extract native libraries, res=-113

I think this problem is because you want to install an arm apk on a x86 cpu.

first solution, try to find the apk but for x86 version cpu, if it really doesn't exist you can use arm native bridge like libndk or libhoudini to run an arm apps on a x86 cpu.

note: you need android 11 to use libhoudini, if you use android 10 you can only use libndk.

go here for installation guide https://github.com/casualsnek/waydroid_script

**Comment by aleasto** [comment]
The comment by cniw is correct.
