### ISSUE TITLE
Installation fails under Debian bookworm

### ISSUE THREAD

**Issue by schtobia** [waydroid/waydroid#361]
**Describe the bug**
It's not possible to install waydroid on the current Debian testing due to unmet dependencies in `python3-gbinder`.

**General information (please complete the following information):**
```
$ LANG=C sudo apt install waydroid
[sudo] password for schtobia: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python3-gbinder : Depends: python3 (< 3.10) but 3.10.4-1 is to be installed
E: Unable to correct problems, you have held broken packages.
```
This is expected, as `python3-gbinder` explicitly prohibits Python 3.10:
```
$ apt-cache show python3-gbinder
Package: python3-gbinder
[…]
Depends: libc6 (>= 2.4), libgbinder, python3 (<< 3.10), python3 (>= 3.9~)
[…]
```

**Desktop (please complete the following information):**
 - OS: Debian 12 "bookworm"
 - GPU: n/a
 - Kernel version: [5.16.18-1](https://packages.debian.org/de/bookworm/linux-image-amd64)
 - Host mesa version: n/a
 - Desktop: LxQt 30
 - Python: [3.10.4-1](https://packages.debian.org/bookworm/python3)

**Comment by Kirigiri-Kyoko** [comment]
i managed to make it install on sid by unpacking the deb packages and changing every script referring to `python3` to `python3.9`, as well as editing the control file for python3-gbinder.

i was able to run `waydroid init` afterwards and everything seems to work fine

**Comment by Armin-0401** [comment]
> 

could u please show the steps of this soulution?
i have the same problem.

**Comment by Armin-0401** [comment]
> i managed to make it install on sid by unpacking the deb packages and changing every script referring to `python3` to `python3.9`, as well as editing the control file for python3-gbinder.
> 
> i was able to run `waydroid init` afterwards and everything seems to work fine

could u please show the steps of this soulution?
i have the same problem.

**Comment by Kirigiri-Kyoko** [comment]
i added the waydroid repo as the guide said, and then i made a new folder and ran:
```
apt download python3-gbinder
dpkg-deb -x python3-gbinder[whatever version the package is].deb unpack
dpkg-deb --control python3-gbinder[version].deb
mv DEBIAN unpack/
```
then i edited unpack/DEBIAN/control to replace all the python3 stuff in the depends field with `python3.9`
then i ran `dpkg -b unpack python3-gbinder-fixed.deb` and installed it normally with `sudo apt install ./python3-gbinder-fixed.deb`

i also unpacked waydroid itself using the same steps and edited `unpack/DEBIAN/postinst`, `unpack/DEBIAN/prerm`, and `unpack/usr/bin/waydroid` changing every instance of `python3` to `python3.9` and additionally changing `py3clean` and `py3compile` to `python3.9 /usr/bin/py3clean` and `python3.9 /usr/bin/py3compile` just to be safe

its a hacky fix but it did work on my end, this should also work for ubuntu 22.04 since it is based on debian bookworm although i have not personally tested it. but it seems like the same issue for both.

until the waydroid devs get python3-gbinder working with python3.10, this is the best fix i can find

**Comment by Kirigiri-Kyoko** [comment]
it WILL constantly say python3-gbinder is out of date though but it will be held back every time

**Comment by aleasto** [comment]
This was fixed
