### ISSUE TITLE
a few questios

### ISSUE THREAD

**Issue by logan001** [waydroid/waydroid#393]
Why some apps are missing from google play store? (like netflix)
Google emulators seems to have these apps in store

How can i install/start multiple emulators?

How can i factory reset one?

how can i resize one? i'm on x11 and start weston and then the waydroid interface but is always in full screen. 

edit:
keyboard is bugged. sometimes i get only beta characters and nothing else. sometimes the keyboard works.

edit 2:
internet access seems to be limited. i can access some sites. i have pppoe on the system and network managers is disabled.

**Comment by cniw** [comment]
> Why some apps are missing from google play store? (like netflix) Google emulators seems to have these apps in store

i assume you're running waydroid on x86 cpu architecture, while google play store only show apps that support your cpu architecture.
you should already know that android is build for gadget with arm cpu, so most of android application are build for arm cpu and only some of it that support x86 or both arm and x86.
you still can run arm apps. on x86 cpu use arm native bridge like libndk or libhoudini, read more https://github.com/casualsnek/waydroid_script
to make it also listed in play store you may need many workaround like cpu spoofing, an even some apps need device spoofing, and more.

---

> How can i install/start multiple emulators?

currently not support by current state of waydroid

---

> How can i factory reset one?

to clean android apps data `rm -rf  ~/.local/share/{waydroid,applications/*aydroid*}`
to clean waydroid image `sudo rm -rf /var/lib/waydroid/`

---

> how can i resize one? i'm on x11 and start weston and then the waydroid interface but is always in full screen.

example make it waydroid screen portrait
make sure waydroid session already running, then open terminal to run these command
`waydroid prop set persist.waydroid.width 432`
`waydroid prop set persist.waydroid.height 768`
or you can use padding too, so waydroid wouldn't overlaped your desktop panel or dock apps
`waydroid prop set persist.waydroid.height_padding 48`
then restart the waydroid session
`waydroid session stop && waydroid show-full-ui`

---

> keyboard is bugged. sometimes i get only beta characters and nothing else. sometimes the keyboard works.

press `Alt` key on your keyboard, it should help make it works normal again.

---

> internet access seems to be limited. i can access some sites. i have pppoe on the system and network managers is disabled.

not so sure because there could be many reasons regarding this problem.

---

@logan001 I think this is not good, asking multiple topic in single issue thread.

to do more dicussion you can go to:
- telegram channel https://t.me/WayDroid
- matrix room https://matrix.to/#/#waydroid:mrcyjanek.net

**Comment by logan001** [comment]
i thought that the image of x86 has the translation for arm cpus.

the problem with the internet is very serious cause besides the browser thing even games can't download necessary files.

**Comment by logan001** [comment]
i managed to fix the internet using the same way i use for softAP.

now i can't make the arm translation to work. the script seems to copy the files but its still not working.

**Comment by Quackdoc** [comment]
It sounds like the chat groups might be more useful for you as stated. you are welcome to come chat there. however can this be closed? if you are experiening other issues, check for issues with similar issues, and comment on them instead of just dumping here. 

this should be closed

**Comment by logan001** [comment]
yeap. i'm closing this. i hope there will be an entry in readme about how to use multiple instances when it will be available.
well most of the issues i found were close with solve or something and no explanation on it.

**Comment by pktiuk** [comment]
Pieces of information in comment of @cniw  are incredibly useful.  

I think it would be great to put them in some kind of official FAQ. I was looking for some of these information in https://docs.waydro.id/
