### ISSUE TITLE
password for livecd

### ISSUE THREAD

**Issue by rogeriojlle** [waydroid/waydroid#394]
the live-cd is asking for a password

**Comment by electrikjesus** [comment]
Try checking out the readme where you downloaded the ISO

**Comment by electrikjesus** [comment]
Try checking out the readme where you downloaded the ISO

**Comment by rogeriojlle** [comment]
> Where in the frickin' world is the readme file???????????????????????????????????????????????????,

![image](https://user-images.githubusercontent.com/562996/236679312-421a23f2-3601-43ef-b896-a04215de722e.png)

**Comment by cniw** [comment]
This is user&pass just example for `waydroid-linux-debian-bookworm-lineage-17.1-vanilla-amd64_2022-03-15_1121.iso`

If  you're using other version go check it directly on https://sourceforge.net/projects/blissos-dev/files/waydroid/linux/
because it may use different user&pass

![Screenshot_20230507_213201](https://user-images.githubusercontent.com/25974007/236684780-381d9a34-e68c-4ecc-980d-a6438cdaabca.png)

**Comment by speedery** [comment]
the password is: evolution

**Comment by robirbf** [comment]
> the password is: evolution

nice is working
