### ISSUE TITLE
Occassionally infinite reboot

### ISSUE THREAD

**Issue by UlyssesZh** [waydroid/waydroid#410]
There are some known occassions where Waydroid will end up infinitely rebooting. The infinite rebooting can be rescued by forcing to stop the session, and next time the waydroid session will be normal.

Some known occassions to lead to infinite rebooting (can be stably reproduced on my device):
1. click "Device hostname" in developer options.
2. click the logged-in google account at the first launch of Google Chrome.

In `waydroid log`, I cannot see anything happening when it infinitely reboots.

Some general info:
 - Waydroid tools Version: 1.2.1
 - Waydroid Images Version: 20220515-GAPPS-waydroid_x86_64
 - OS: Ubuntu 20.04 x64
 - Kernel version: 5.13.0-48-generic

Prop file:
```
sys.use_memfd=true
debug.stagefright.ccodec=0
ro.hardware.gralloc=default
ro.hardware.egl=swiftshader
ro.hardware.camera=v4l2
ro.opengles.version=196608
waydroid.system_ota=https://ota.waydro.id/system/lineage/waydroid_x86_64/GAPPS.json
waydroid.vendor_ota=https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
waydroid.tools_version=1.2.1
ro.vndk.lite=true
waydroid.active_apps=Waydroid
```

**Comment by aleasto** [comment]
Please reopen and attach `sudo waydroid logcat` if still reproducible

**Comment by carafelix** [comment]
Happend to me on Ubuntu 22.02.
How to reproduce: 
- Open calendar (maybe other apps too) via the applications menu (Super +A: 'way')
- Close calendar via app dock
- Close waydroid.com.android.launcher3 any way, it reopens infinitely




`07-20 15:27:46.300   275   364 I InputReader: Dropping key up from device wayland_keyboard because the key was not down.  keyCode=24, scanCode=115
07-20 15:27:46.659  1094  1094 W KeyboardSwitcher: onToggleKeyboard() : Current = EMOJI : Toggle = EMOJI
07-20 15:27:56.692  1880  1902 W System.err: java.net.ConnectException: Failed to connect to ota.waydro.id/185.199.108.153:443
07-20 15:27:56.692  1880  1902 W System.err: 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:147)
07-20 15:27:56.692  1880  1902 W System.err: 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
07-20 15:27:56.692  1880  1902 W System.err: 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
07-20 15:27:56.692  1880  1902 W System.err: 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
07-20 15:27:56.692  1880  1902 W System.err: 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
07-20 15:27:56.692  1880  1902 W System.err: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
07-20 15:27:56.692  1880  1902 W System.err: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
07-20 15:27:56.692  1880  1902 W System.err: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
07-20 15:27:56.692  1880  1902 W System.err: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
07-20 15:27:56.692  1880  1902 W System.err: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
07-20 15:27:56.692  1880  1902 W System.err: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
07-20 15:27:56.692  1880  1902 W System.err: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
07-20 15:27:56.692  1880  1902 W System.err: 	at java.net.URL.openStream(URL.java:1072)
07-20 15:27:56.692  1880  1902 W System.err: 	at org.lineageos.waydroidupdater.UpdaterTools.readJsonFromUrl(UpdaterTools.java:66)
07-20 15:27:56.693  1880  1902 W System.err: 	at org.lineageos.waydroidupdater.UpdaterTools.fetchUpdates(UpdaterTools.java:43)
07-20 15:27:56.693  1880  1902 W System.err: 	at org.lineageos.waydroidupdater.BootReceiver.lambda$onReceive$0(BootReceiver.java:20)
07-20 15:27:56.693  1880  1902 W System.err: 	at org.lineageos.waydroidupdater.-$$Lambda$BootReceiver$1EBKxaSoMeFPvwxntCC4sggxq6M.run(Unknown Source:2)
07-20 15:27:56.693  1880  1902 W System.err: 	at java.lang.Thread.run(Thread.java:923)
07-20 15:27:57.803   275   363 D InputDispatcher: Waiting to send key to Window{ee62882 u0 com.android.launcher3/com.android.launcher3.uioverrides.QuickstepLauncher} because there are unprocessed events that may cause focus to change
07-20 15:27:57.807   275   364 I InputReader: Dropping key up from device wayland_keyboard because the key was not down.  keyCode=0, scanCode=190
07-20 15:27:57.806   275  1127 E TaskPersister: File error accessing recents directory (directory doesn't exist?).
07-20 15:27:57.808   275   344 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10000100 cmp=com.android.launcher3/.uioverrides.QuickstepLauncher} from uid 0
07-20 15:27:57.812   275   344 E BoringdroidConfig: Don't save package windowing mode when pc mode disabled
07-20 15:27:57.812   275   344 W ActivityTaskManager: Tried to set launchTime (0) < mLastActivityLaunchTime (960826)
07-20 15:27:57.824   275   363 W InputDispatcher: Waiting because no window has focus but ActivityRecord{59c2f06 u0 com.android.launcher3/.uioverrides.QuickstepLauncher t31} may eventually add a window when it finishes starting up. Will wait for 5000ms
07-20 15:27:57.824   275   363 W InputDispatcher: Still no focused window. Will drop the event in 4999ms
07-20 15:27:57.831   870   870 D RecentsOrientedState: current RecentsOrientedState: [this=RecentsOrientedState@8e10e45 mOrientationHandler=PortraitPagedViewHandler@58f0656 mDisplayRotation=0 mTouchRotation=0 mRecentsActivityRotation=0 isRecentsActivityRotationAllowed=true mSystemRotation=false mFlags=257]
07-20 15:27:57.832   870   870 D RecentsOrientedState: current RecentsOrientedState: [this=RecentsOrientedState@8e10e45 mOrientationHandler=PortraitPagedViewHandler@58f0656 mDisplayRotation=0 mTouchRotation=0 mRecentsActivityRotation=0 isRecentsActivityRotationAllowed=true mSystemRotation=false mFlags=257]
07-20 15:27:57.836   275   363 W InputDispatcher: Still no focused window. Will drop the event in 4988ms
07-20 15:27:57.850   870   870 E libprocessgroup: set_timerslack_ns write failed: Operation not permitted
07-20 15:27:57.852   275   363 W InputDispatcher: Still no focused window. Will drop the event in 4971ms
07-20 15:27:57.862   870   870 I android_os_HwBinder: HwBinder: Starting hwbinderthread pool for getting: vendor.waydroid.window@1.1::IWaydroidWindow/default
07-20 15:27:57.867   275  2301 W ActivityManager: Unable to start service Intent { act=com.android.launcher3.WINDOW_OVERLAY dat=app://com.android.launcher3:10125?v=9&cv=14 pkg=com.google.android.googlequicksearchbox } U=0: not found
07-20 15:27:57.870   275   344 W ActivityManager: Unable to start service Intent { act=com.android.launcher3.WINDOW_OVERLAY dat=app://com.android.launcher3:10125?v=9&cv=14 pkg=com.google.android.googlequicksearchbox } U=0: not found
07-20 15:27:57.874   275   363 W InputDispatcher: Still no focused window. Will drop the event in 4950ms
07-20 15:27:57.876   275   363 W InputDispatcher: Still no focused window. Will drop the event in 4947ms
07-20 15:27:57.877   275   363 W InputDispatcher: Still no focused window. Will drop the event in 4947ms
07-20 15:27:57.886   275   363 W InputDispatcher: Still no focused window. Will drop the event in 4938ms
07-20 15:27:57.902   275   363 W InputDispatcher: Still no focused window. Will drop the event in 4921ms
07-20 15:27:57.914   275   322 I ActivityTaskManager: Displayed com.android.launcher3/.uioverrides.QuickstepLauncher: +104ms
07-20 15:27:57.920   275   363 W InputDispatcher: Still no focused window. Will drop the event in 4903ms
07-20 15:27:57.920   275   363 W InputDispatcher: Still no focused window. Will drop the event in 4903ms
07-20 15:27:57.920   275   363 D InputDispatcher: Waiting to send key to Window{b20f3db u0 com.android.launcher3/com.android.launcher3.uioverrides.QuickstepLauncher} because there are unprocessed events that may cause focus to change
07-20 15:27:57.931   870   870 E libprocessgroup: set_timerslack_ns write failed: Operation not permitted
07-20 15:27:58.134   275   364 I InputReader: Dropping key up from device wayland_keyboard because the key was not down.  keyCode=57, scanCode=56
07-20 15:28:00.002   480   480 D KeyguardClockSwitch: Updating clock: 3:28
07-20 15:28:01.014   275  1127 E TaskPersister: File error accessing recents directory (directory doesn't exist?).


`
