### ISSUE TITLE
Waydroid or WayDroid?

### ISSUE THREAD

**Issue by kj7rrv** [waydroid/waydroid#443]
What is the correct capitalization of the name?

**Comment by kj7rrv** [comment]
It looks like Waydroid is used more often.

**Comment by apy7hst** [comment]
Even the waydroid logo pronounces the word as "Waydroid" only, so the term Waydroid can be used. By the way, this should be discussed in the waydroid [telegram](https://t.me/Waydroid) / [matrix](https://matrix.to/#/#waydroid:mrcyjanek.net) group because opening issues only for tiny doubts like this one makes it hard for members to manage, help or close issues.

**Comment by kj7rrv** [comment]
Okay, thank you.
