### ISSUE TITLE
Weird behavior on ubuntu

### ISSUE THREAD

**Issue by jhay06** [waydroid/waydroid#465]
Hi , 
  I just installed waydroid on ubuntu 22.04 

I found out that i can install libndk to work the arm built apps on the waydroid  since it is android 10 

but when checking ,  installing some arm apps on it , some works some not using the default configuration 

but after changing waydroid.cfg to add this 
ro.hardware.gralloc=default
ro.hardware.egl=swiftshader

apps works but laggy and per checking that config is for VM 

and im not using VM to run waydroid

what should i do to work without the parameter ?

**Comment by cniw** [comment]
> apps works but laggy

You're running arm apps on x86 cpu using libndk which mean it running using emulation which increases the CPU workload

----

> and per checking that config is for VM
> 
> and im not using VM to run waydroid

It not only use for VM, that properties supposed to use on unsuported graphics device card eg. Nvidia, some AMD and generic graphics on VM by using software rendering instead of iGPU/dGPU it will use CPU and again will increases the CPU workload

---

> what should i do to work without the parameter ?

Change that properties in `waydroid.cfg` file or just remove it

```cfg
ro.hardware.gralloc=gbm
ro.hardware.egl=mesa
```

Use your GPU as much as possible, what is your graphics card `lspci -k | awk '/(VGA|3D|Display)/,/modules/'`?

**Comment by aleasto** [comment]
Missing information, but if you had games crashing it's probably fixed in the latest Android 11 images
