### ISSUE TITLE
cannot init waydroid

### ISSUE THREAD

**Issue by richou672005** [waydroid/waydroid#555]
hi
I installed waydroid on my fedora(nobara) and in cannot init it: 
-by using systemctl enable waydroid i get that waydroid.service does not exist 
-by typing sudo waydroid init -s GAPPS i get :
ERROR: Failed to get system OTA channel: /lineage/waydroid_x86_64/GAPPS.json, error: -1

**Comment by Anifyuli** [comment]
You can try tutorials on this web [Waydroid on Fedora - Reisuke](https://www.reisuke.com/waydroid-fedora/)

**Comment by Quackdoc** [comment]
follow the docs on the waydroid copr repo

**Comment by axelsimon** [comment]
For a start, `sudo waydroid init` should be enough to initialise waydroid, considering it the command has some default values set:
```
 -c SYSTEM_CHANNEL (…) (default is Official OTA server)
 -v VENDOR_CHANNEL (…) (default is Official OTA server)
 -r ROM_TYPE (…) (default is LineageOS)
 -s SYSTEM_TYPE (…) (default is VANILLA)
```
Beyond that, if one needs to know some _secret sauce_ values to initialise the app, there's a UX problem somewhere. The good thing is that that, in fact, is not the case, defaults exist. And while the GUI doesn't pre-fill the fields or explicitly tell you there are defaults for SYSTEM and VENDOR, it does use them, AFAICT.

So the problem appears to lie elsewhere, because running `sudo waydroid init` results in `ERROR: Failed to get system OTA channel: /lineage/waydroid_x86_64/VANILLA.json, error: -1`. There appears to be a problem reaching https://ota.waydro.id/system/lineage/waydroid_x86_64/VANILLA.json from `waydroid`, while a `curl` to the same URL works fine.

One more thing, the docs on the [copr repo](https://copr.fedorainfracloud.org/coprs/aleasto/waydroid/) or on the [Reisuke Waydroid Fedora article](https://www.reisuke.com/waydroid-fedora/) don't provide any help here, they just say to use https://ota.waydro.id/system and https://ota.waydro.id/vendor as init URLs, which goes nowhere (GUI stays stuck on `Waiting for waydroid container service...`, and `sudo waydroid init -c https://ota.waydro.id/system -v https://ota.waydro.id/vendor` does nothing.

**Comment by richou672005** [comment]
okay thx , i'm realy sorry i didnt read the tutorial correctly,

**Comment by picklefan** [comment]
> It turns out my IPv6 routing was broken, but Python didn't know that so just tried to connect to Sourceforge over IPv6, failed, and just stayed there waiting. After removing IPv6 routing, the images downloaded fine and Waydroid now starts.

I've been stuck on `waydroid init` and it outputted nothing, so I had zero clue what the problems may be until I saw this thread. My problem is also IPv6 network issue, which I would never find out all by myself. 
I wonder if you can kindly tell me how did you find out that it was caused by network issue as I am too noob to figure it out even now.
I hope this message would not cause you any inconvenience and I wish you a good day.

**Comment by tsilvs** [comment]
I am having this issue on Fedora Silverblue right now, and it seems it's not caused by anything tied to IPv6.

If anyone had solved it, I'd like to know how.

**Comment by NiaTheCat** [comment]
> Upd: seems like this solves the issue: https://docs.waydro.id/usage/install-on-desktops#fedora

This solves the issue on Fedora 39 non-silverblue variant as well.

**Comment by SeriousProgramer** [comment]
sudo waydroid init -c 'https://ota.waydro.id/system' -v 'https://ota.waydro.id/vendor'

worked for me
