### ISSUE TITLE
Waydroid container fails to start.

### ISSUE THREAD

**Issue by Oksino** [waydroid/waydroid#690]
Whenever I run `waydroid session start` with `sudo waydroid container start` or `waydroid first-launch`. The container fails to start with this log
````
which: no iptables-legacy in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin)
which: no ip6tables-legacy in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin)
Warning: ZONE_ALREADY_SET: 'waydroid0' already bound to 'trusted'
success

dnsmasq: failed to open pidfile /run/waydroid-lxc/dnsmasq.pid: Permission denied
Failed to setup waydroid-net.
Failed to setup waydroid-net.
(004485) [11:19:20] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(004485) [11:19:20] % umount /var/lib/waydroid/rootfs/vendor
(004485) [11:19:20] % umount /var/lib/waydroid/rootfs
(004485) [11:19:20] % mount -o context="system_u:object_r:waydroid_rootfs_t:s0" /usr/share/waydroid-extra/images/system.img /var/lib/waydroid/rootfs
(004485) [11:19:20] % mount -o remount,ro /usr/share/waydroid-extra/images/system.img /var/lib/waydroid/rootfs
(004485) [11:19:20] % mount -o context="system_u:object_r:waydroid_rootfs_t:s0" /usr/share/waydroid-extra/images/vendor.img /var/lib/waydroid/rootfs/vendor
(004485) [11:19:21] % mount -o remount,ro /usr/share/waydroid-extra/images/vendor.img /var/lib/waydroid/rootfs/vendor
(004485) [11:19:21] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(004485) [11:19:21] Save config: /var/lib/waydroid/waydroid.cfg
(004485) [11:19:21] % chmod 777 -R /dev/dri
(004485) [11:19:21] % chmod 777 -R /dev/fb0
(004485) [11:19:21] % chmod 777 -R /dev/video1
(004485) [11:19:21] % chmod 777 -R /dev/video0
(004485) [11:19:21] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(004485) [11:19:21] New background process: pid=4580, output=background
lxc-start: waydroid: network.c: netdev_configure_server_veth: 710 No such file or directory - Failed to attach "vethJXkvxW" to bridge "waydroid0", bridge interface doesn't exist
lxc-start: waydroid: network.c: lxc_create_network_priv: 3413 No such file or directory - Failed to create network device
lxc-start: waydroid: start.c: lxc_spawn: 1843 Failed to create the network
lxc-start: waydroid: start.c: __lxc_start: 2074 Failed to spawn container "waydroid"
lxc-start: waydroid: conf.c: run_buffer: 321 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 988 Failed to run lxc.hook.post-stop for container "waydroid"
lxc-start: waydroid: tools/lxc_start.c: main: 306 The container failed to start
lxc-start: waydroid: tools/lxc_start.c: main: 311 Additional information can be obtained by setting the --logfile and --logpriority options
(004485) [11:19:21] waiting 10 seconds for container to start...
(004485) [11:19:22] waiting 9 seconds for container to start...
(004485) [11:19:23] waiting 8 seconds for container to start...
(004485) [11:19:24] waiting 7 seconds for container to start...
(004485) [11:19:25] waiting 6 seconds for container to start...
(004485) [11:19:26] waiting 5 seconds for container to start...
(004485) [11:19:27] waiting 4 seconds for container to start...
(004485) [11:19:28] waiting 3 seconds for container to start...
(004485) [11:19:29] waiting 2 seconds for container to start...
(004485) [11:19:30] waiting 1 seconds for container to start...
(004485) [11:19:31] ERROR: container failed to start
(004485) [11:19:31] See also: <https://github.com/waydroid>
(004485) [11:19:31] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 68, in main
    actions.container_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 131, in start
    raise OSError("container failed to start")
OSError: container failed to start

(004659) [11:19:39] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(004659) [11:19:39] *** output passed to waydroid stdout, not to this log ***
(005431) [11:25:22] WAYLAND_DISPLAY is not set, defaulting to "wayland-0"
(005431) [11:25:22] Save session config: /var/lib/waydroid/session.cfg
(005431) [11:25:22] UserMonitor service is not even started
(005431) [11:25:22] Clipboard service is not even started
(005431) [11:25:37] UserMonitor service is not even started
(005431) [11:25:37] Clipboard service is not even started
(005553) [11:27:39] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(005553) [11:27:39] *** output passed to waydroid stdout, not to this log ***
```

**Comment by aleasto** [comment]
https://docs.waydro.id/debugging/known-issues#container-fails-to-start-dnsmasq-cannot-open-pid-file

**Comment by compata** [comment]
Solution offered does not help me. Fedora 37 with KDE.

$ waydroid show-full-ui
[19:43:02] Starting waydroid session
^C

(033233) [19:48:56] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(033233) [19:48:56] *** output passed to waydroid stdout, not to this log ***
(031600) [19:54:45] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH STOPPED
(031600) [19:54:45] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop vnic is waydroid0
(031600) [19:54:45] % systemctl is-enabled -q nfcd Failed to get unit file state for nfcd.service: No such file or directory
(031600) [19:54:45] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(031600) [19:54:45] % umount /var/lib/waydroid/rootfs/vendor
(031600) [19:54:45] % umount /var/lib/waydroid/rootfs/vendor
(031600) [19:54:46] % umount /var/lib/waydroid/rootfs
(031600) [19:54:46] % umount /var/lib/waydroid/rootfs

# waydroid status
Session:        RUNNING
Container:      STOPPED
Vendor type:    MAINLINE
Session user:   dave(1000)

# systemctl status waydroid-container
● waydroid-container.service - Waydroid Container
     Loaded: loaded (/usr/lib/systemd/system/waydroid-container.service; enabled; preset: disabled)
     Active: active (running) since Sun 2023-03-26 19:42:45 PDT; 22min ago
    Process: 31599 ExecStartPre=/usr/bin/ln -sf /dev/binderfs/binder /dev/binderfs/vndbinder /dev/binderfs/hwbinder /dev/ (code=exited, status=0/SUCCESS)
   Main PID: 31600 (waydroid)
      Tasks: 3 (limit: 9439)
     Memory: 16.4M
        CPU: 1.001s
     CGroup: /system.slice/waydroid-container.service
             └─31600 /usr/bin/python3 /usr/bin/waydroid -w container start

# waydroid container start
ERROR: WayDroid container service is already running

# ls /etc/apparmor*
/usr/bin/ls: cannot access '/etc/apparmor*': No such file or directory

# waydroid log
STOPPED
(019804) [19:36:27] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(019804) [19:42:36] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(019804) [19:42:36] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop
vnic is waydroid0
(019804) [19:42:36] % systemctl is-enabled -q nfcd
Failed to get unit file state for nfcd.service: No such file or directory
(019804) [19:42:36] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(019804) [19:42:36] % umount /var/lib/waydroid/rootfs/vendor
(019804) [19:42:36] % umount /var/lib/waydroid/rootfs/vendor
(019804) [19:42:36] % umount /var/lib/waydroid/rootfs
(019804) [19:42:36] % umount /var/lib/waydroid/rootfs
(029340) [19:42:36] Introspect error on :1.635:/ContainerManager: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Remote peer disconnected
(029340) [19:42:36] Executing introspect queue due to error
(031600) [19:42:45] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(031600) [19:42:45] % modprobe -q ashmem_linux
(031600) [19:42:45] % chmod 666 -R /dev/binder
(031600) [19:42:45] % chmod 666 -R /dev/vndbinder
(031600) [19:42:45] % chmod 666 -R /dev/hwbinder
(031666) [19:43:02] Starting waydroid session
(031600) [19:43:02] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
Warning: ZONE_ALREADY_SET: 'waydroid0' already bound to 'trusted'
success
(031600) [19:43:03] % systemctl is-active -q nfcd
(031600) [19:43:03] % chmod 777 -R /dev/dri
(031600) [19:43:03] % chmod 777 -R /dev/fb0
(031600) [19:43:03] % mv /var/lib/waydroid/config_session /var/lib/waydroid/lxc/waydroid
(031600) [19:43:03] % mount -o context="system_u:object_r:waydroid_rootfs_t:s0",ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(031600) [19:43:03] % mount -t overlay -o context="system_u:object_r:waydroid_rootfs_t:s0",ro,lowerdir=/var/lib/waydroid/overlay:/var/lib/waydroid/rootfs,upperdir=/var/lib/waydroid/overlay_rw/system,workdir=/var/lib/waydroid/overlay_work/system,xino=off overlay /var/lib/waydroid/rootfs
(031600) [19:43:03] % mount -o context="system_u:object_r:waydroid_rootfs_t:s0",ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(031600) [19:43:03] % mount -t overlay -o context="system_u:object_r:waydroid_rootfs_t:s0",ro,lowerdir=/var/lib/waydroid/overlay/vendor:/var/lib/waydroid/rootfs/vendor,upperdir=/var/lib/waydroid/overlay_rw/vendor,workdir=/var/lib/waydroid/overlay_work/vendor,xino=off overlay /var/lib/waydroid/rootfs/vendor
(031600) [19:43:03] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(031600) [19:43:03] Save config: /var/lib/waydroid/waydroid.cfg
(031600) [19:43:03] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(031600) [19:43:03] New background process: pid=31734, output=background
(031600) [19:43:03] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
lxc-start: waydroid: conf.c: run_buffer: 321 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 988 Failed to run lxc.hook.post-stop for container "waydroid"
(031600) [19:43:08] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(033233) [19:48:56] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(033233) [19:48:56] *** output passed to waydroid stdout, not to this log ***
(031600) [19:54:45] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(031600) [19:54:45] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop
vnic is waydroid0
(031600) [19:54:45] % systemctl is-enabled -q nfcd
Failed to get unit file state for nfcd.service: No such file or directory
(031600) [19:54:45] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(031600) [19:54:45] % umount /var/lib/waydroid/rootfs/vendor
(031600) [19:54:45] % umount /var/lib/waydroid/rootfs/vendor
(031600) [19:54:46] % umount /var/lib/waydroid/rootfs
(031600) [19:54:46] % umount /var/lib/waydroid/rootfs
(039102) [20:07:19] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(039102) [20:07:19] *** output passed to waydroid stdout, not to this log ***

# dnf provides */nfcd.service
Last metadata expiration check: 3:19:34 ago on Sun 26 Mar 2023 04:50:12 PM PDT.
Error: No matches found.
