### ISSUE TITLE
[Feature request] Separate launchers for each app

### ISSUE THREAD

**Issue by CactiChameleon9** [waydroid/waydroid#7]
Like the original anbox, the ability to open apps in their own separate windows so they integrate with the host OS better.

**Comment by CactiChameleon9** [comment]
Well, I just saw this: https://github.com/Anbox-halium/android_device_halium_anbox/commit/2c284460743394eac3aeaad2fe003a8a8820df66
Could it be related?

**Comment by Dinibewerbig** [comment]
Hi, Cacti. What are the steps I have to take to install waydroid on linux ubuntu. The instructions aren't clear at all... Please help me out here.

**Comment by CactiChameleon9** [comment]
@Dinibewerbig What makes you think I have a clue about how to install waydroid on ubuntu. I was testing on drodian & ubuntu touch (linux mobile devices), not normal ubuntu.

 I don't know if the ubuntu kernel is patched correctly, but if it is then running this script may work: https://github.com/waydroid/anbox-halium/blob/lineage-17.1/scripts/install.sh as I have said, I have no clue about running this on ubuntu.

**Comment by erfanoabdi** [comment]
Feature added

**Comment by Quoteme** [comment]
> Feature added

Are you referring to 9447b7cfccfb6bbd930cff4a4a15206233d2257c? Or is it any ov the other commits from Sep 4 2021 (listed here: https://github.com/waydroid/waydroid/commits/main?after=b67b4415c1aef525153cc156806ef7e41f38756c+244&branch=main&qualified_name=refs%2Fheads%2Fmain#)?

I am asking, because I would like to have a separate window in my desktop environment for each app. Is the feature discussed here the feature, that the waydroid launcher can be run [in Multi-Window Mode](https://docs.waydro.id/usage/install-on-desktops#launch-waydroid-in-multi-window-mode), because that feature only opens new windows inside the waydroid launcher, not in the desktop environment.
