### ISSUE TITLE
[Unbuntu Touch] Icons & Crashing

### ISSUE THREAD

**Issue by blank1-Dev** [waydroid/waydroid#715]
**Describe the bug**
There is no way to remove any of the icons from the main menu bar (all apps section) in Unbutu touch, even when I try to go to the folders where the .desktop files are. This seems like it should be something I can resolve within the OS to delete the icons I don't want but I can't figure it out, if I'm missing something please inform me. 

Also, if I close Waydroid I cannot open it again until I reboot the phone as it just crashes (does nothing).

**General information (please complete the following information):**
Not sure where to get these, please advise. I did just download today so I likely have the latest as of this post.

**Smartphone (please complete the following information):**
 - Device: Pixel 3a XL
 - OS: Ubuntu touch OTA24
 - Halium 9
 - Kernel version: 4.9.124

**Additional context**
I don't think I can be any clearer, but to simplify:

- Adds lots of icons with no obvious way of removing ones I dont want
- Crashes a lot, mainly after its closed via the app switcher. Requires reboots whenever I accidently close it.

**Logs (please upload as file)**
 - Prop file https://pastebin.com/ZakyAMKd
 - Output of `waydroid log` https://pastebin.com/V9yR2Jic
 - Full Output of `waydroid logcat` https://imgur.com/a/rtLFksT

**Comment by JamiKettunen** [comment]
The icons are stored in `~/.local/share/applications/waydroid.*.desktop`, adding `NoDisplay=true` to end of file will hide the ones you don't want to see. Keep in mind [Waydroid Helper](https://open-store.io/app/waydroidhelper.aaronhafer) exists and makes this process easier.

Also the crashing is a known issue with QtMir (Ubuntu Touch) and it kind of fixed on 20.04 by luck due to a regression in how the session is supposed to work; on 16.04 you can again use Waydroid Helper to create the `Stop Waydroid` launcher item which you'll have to click when you're done/want to open another Waydroid window after closing them all.

**Comment by blank1-Dev** [comment]
@JamiKettunen Thank you. I have managed to figure that out myself.  For those like me who didn't know, ^^^^ above is the workaround for the issue.
