### ISSUE TITLE
Get rid of dnsmasq

### ISSUE THREAD

**Issue by atmouse-** [waydroid/waydroid#77]
Dnsmasq need passthrough the apparmor rules or selinux which most of linux dist included by default.

We can use [DHCPServer] provided by systemd-networkd instead like this
```
[Match]
Name=waydroid0

[Network]
Address=192.168.250.1/24
DHCPServer=true
IPForward=yes

[DHCPServer]
PoolOffset=100
PoolSize=20
EmitDNS=yes
#DNS=8.8.8.8
```

systemd itself is the default init system of most dist ubuntu debian arch also Halium

**Comment by Nidrop** [comment]
Disagree. I want to use waydroid in my Void linux (runit). Also i noticed some Alpine (openrc) users here in issues

**Comment by Quackdoc** [comment]
This wound up falling under the radar, this should possible now by modifying `/var/lib/waydroid/lxc/waydroid/config` changing the interface to waydroid0 to something else, this will allow you to setup your own networks instead of relying on waydroid-net to do so. 

if you wanted to do this, feel free to make a brief write up and I would be happy to make a PR to add it to the docs.
