### ISSUE TITLE
installing waydroid on kali linux

### ISSUE THREAD

**Issue by kibo1no1shirei-kan** [waydroid/waydroid#779]
**Describe the bug**
Despite me running the commnand 
sudo apt install waydroid -y
an error pops up "E: Unable to locate package waydroid"

**Screenshots**
![image](https://user-images.githubusercontent.com/96419861/221067956-4b76c968-2382-466c-88f2-7ff59f765222.png)
![image](https://user-images.githubusercontent.com/96419861/221068099-c30adb6d-d5c5-46ae-b079-2818cc718545.png)
![image](https://user-images.githubusercontent.com/96419861/221068237-95ae01fc-9399-4b03-8bce-34b71b988fbf.png)**General information (please complete the following information):**
 - Waydroid tools Version [e.g. 1.1.0]
 - Waydroid Images Version [e.g. VANILLA 20211021], or `system_datetime`/`vendor_datetime` from `/var/lib/waydroid/waydroid.cfg`
na
**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 x64]
 - GPU: [e.g. AMD Radeon™ RX 5700]
 - Kernel version: [e.g. Generic 5.4.x]
 - Host mesa version: [e.g. mesa 2.2]
 - Desktop: [e.g. Gnome 40.x.x]
![image](https://user-images.githubusercontent.com/96419861/221068223-6b7b412e-9f06-420a-a2d3-251f3d2f3bfa.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 3a]
 - OS: [e.g. Ubuntu touch OTA19]
 - Mainline or Halium [e.g. Halium 9]
 - Kernel version: [e.g. 4.14.x]

**Additional context**

**Logs (please upload as file)**
 - Prop file, located at `/var/lib/waydroid/waydroid.prop`. In case that doesn't exist, use `/var/lib/waydroid/waydroid_base.prop` instead
 - Log file, located at `/var/lib/waydroid/waydroid.log`
 - *Full* (not partial) output of `waydroid logcat` while Waydroid is running
 - Output of `dmesg`

**Comment by aleasto** [comment]
https://docs.waydro.id

**Comment by richdear** [comment]
I have same issue & the link doesn't help

**Comment by SelfishCoconut** [comment]
Following the [official documentation](https://docs.waydro.id/usage/install-on-desktops#ubuntu-debian-and-derivatives) you should:

- Add the official repository
```
curl -s https://repo.waydro.id | sudo bash -s trixie
```
_Notice in this case, we specify '**-s trixie**' given that otherwise it doesnt work on kali-rolling._ 

- Install waydroid
```
sudo apt install waydroid -y
```

That did it for me.

**Comment by SelfishCoconut** [comment]
Later on I found other problems related to wayland.
```
└─$ waydroid session start
[13:28:38] WAYLAND_DISPLAY is not set, defaulting to "wayland-0"
[13:28:38] Wayland socket '/run/user/1000/wayland-0' doesn't exist; are you running a Wayland compositor?
``` 

For which I found a solution on this video:
https://youtu.be/XbMvIqQ-8xU

I put together a simple tutorial to have it up and running.

### Waydroid Installation on Kali

Execute the following commands to install waydroid:
```
sudo apt install curl ca-certificates -y
curl -s https://repo.waydro.id | sudo bash -s trixie
sudo apt install waydroid -y
```
```
sudo systemctl restart waydroid-container
```
Since in kali linux we use X11, we will need weston:

```
sudo apt install weston
```
```
weston
```

In the weston window, click top left corner to open terminal and type:
```
sudo systemctl start waydroid-container
waydroid session start
```
Lastly, run waydroid from Start Menu

That should do it :)

![Image](https://github.com/user-attachments/assets/e355f167-6c86-4b79-85ae-603becc13c2c)
