### ISSUE TITLE
[DUMB QUESTION] - Include GApps

### ISSUE THREAD

**Issue by anonimo82** [waydroid/waydroid#798]
**Is your feature request related to a problem? Please describe.**
Some Android Apps won't work without Google Play Services 

**Describe the solution you'd like**
Include a Pico/Nano GApps package in the shipped Lineage image, then offer the user to choose the one with or without GApps to install with WayDroid 

**Describe alternatives you've considered**
I tried to manually install the required APKs, knowing in advance it wouldn't have worked, and indeed it didn't 

**Additional context**
I tagged my request as dumb because I ignore the background: there may be compatibility issues I don't know or similar things. If so, please just forget this and forgive me =)

**Comment by HanoJing** [comment]
Just initialize Waydroid with gapps, so:

`sudo waydroid init -s GAPPS` This will give you Waydroid with GAPPS, enjoy!

**Comment by anonimo82** [comment]
Thanks so much, now I feel SO DUMB lol =)

**Comment by HanoJing** [comment]
Not the one who does not know, is dumb, but the one who does not want to know.

You aren't dumb, since you asked.

**Comment by anonimo82** [comment]
Thanks, slim consolation

**Comment by HanoJing** [comment]
It happens, don't beat yourself up about it. Learn from mistakes.

**Comment by anonimo82** [comment]
Yes, for sure!

**Comment by baptx** [comment]
@ghost Your command says "Already initialized" if we already have the VANILLA image installed.
And if we use the "-f" option, I read it replaces the image so we will lose the apps installed and their configuration (https://android.stackexchange.com/questions/248366/how-to-install-google-play-or-other-repos-on-waydroid).
Isn't it possible to install only Google Play Services packages on the VANILLA image of Waydroid instead of installing GAPPS image, like it can be done on Anbox with a script (https://github.com/geeks-r-us/anbox-playstore-installer)?

**Comment by Malix-Labs** [comment]
_Since [discussions](https://github.com/waydroid/waydroid/discussions) has opened, it would be good to move this one to it :)_
