### ISSUE TITLE
wadroid show-full-ui running but the display not in the right position

### ISSUE THREAD

**Issue by maswie** [waydroid/waydroid#81]
I use zorin 16 with  wayland, i success install and run waydroid but the display of waydroid is not in the right position, appears in the lower right half of the screen and it's useless

**Comment by maswie** [comment]
This is my screenshot

![Screenshot from 2021-09-24 06-03-06](https://user-images.githubusercontent.com/28726742/134595068-8392a64a-fa12-452e-8fe9-f98c3efe745a.png)

**Comment by tzcrawford** [comment]
I occasionally get this to happen on pinephone depending on if the squeekboard is open when it spawns. Not quite as bad, but there's no way to resize or move the window as far as I'm aware.
![Screenshot_20210923-223403](https://user-images.githubusercontent.com/33270326/134623564-6f1b0f49-afbc-4b34-8709-9bf4b4918651.png)

**Comment by WebFreak001** [comment]
that issue always happens for me on pinephone with phosh (as the keyboard is open when I type the show ui command and even trying to close it as quickly as possible doesn't make it start in full screen)

**Comment by Theo3113** [comment]
He probado algunas distros con Wayland en sus escritorios, las que presentaban otros inconvenientes, pero esto es algo nuevo. Lo que noté es que en las que usan o Gnome o basados en él, el color de la GUI de Waydroid se torna rojizo, y en el que mejor se ejecutó, dentro de todo, fue en Kubuntu. Sin embargo Ahora con ZorinOS 16 también tengo exactamente el mismo inconveniente, hay que estar para soportar y no abandonar el intento de que funcione correctamente en todos lados no.... Encima justamente el proyecto gira en torno al contenedor, o al menos sobre eso es que tanta publicidad se hace, pero en la realidad es lo que primero falla con solo ver todas las cuestiones acá en Github, siempre con dramas al iniciar.

![Captura](https://user-images.githubusercontent.com/32743726/137138212-ddc1d9ef-e632-4a63-b538-997dc75e1ed5.png)

**Comment by Isrofasil** [comment]
I have the same issue on Zorin OS 16 where the screen is in the bottom right:

![Screenshot from 2021-10-15 22-18-56](https://user-images.githubusercontent.com/92607240/137555042-aed882cc-6391-4a5e-a576-e6096181f8ae.png)

If you want to use the full UI I noticed a work around to get it positioned correctly, once launched and showing as above open Display Settings,  drop the resolution down and apply.  Keep changes.  Then put the resolution back up, apply and keep changes.  The window refreshes to the correct location and size.

![Screenshot from 2021-10-15 22-20-02](https://user-images.githubusercontent.com/92607240/137555377-a6386afe-3e15-4a2c-99b0-a62c56541840.png)

I noticed that the android display resolution does not change when the Zoris OS resolution changes so if you dont change the resolution back in the above steps you wont see the full screen.

**Comment by aleasto** [comment]
Can you verify whether this is still the case with the latest android images?
`sudo waydroid ugprade`

**Comment by eclairevoyant** [comment]
Still occurs on my end. Even if I fullscreen it, the android screen is not aligned to the computer's monitor. (Screenshot below is of the entire monitor)

![2023-01-22_18-50](https://user-images.githubusercontent.com/848000/213947212-77d2397a-28b2-4f13-b309-2d71a6ccc82e.png)

**Comment by Isrofasil** [comment]
I recently found that I can resolve the issue by changing the way new windows are opened, using Gnome Tweaks I turned off Center New Windows and now the android screen is aligned correctly.

**Comment by aleasto** [comment]
Indeed window placement is entirely up to the compositor.

Waydroid opens a maximized window so compositors should be able to easily figure out that it should be placed at the top-left corner, but apparently some (i think only ZorinOS) fail.

There's nothing we can do to influence this behavior.

**Comment by Isrofasil** [comment]
Does Waydroid actually create a maximized window or does it create a small window and then resize it as needed?  

In my testing of running apps rather than the the full android desktop i got the same issue where the top left of the app is in the center of the screen, i assumed that Waydroid actually creates a very small small window which the compositor then aligns to centre before waydroid then expands the window.

**Comment by carpeNoctem01** [comment]
> You can also reposition window with pressing Meta/Super key + dragging window to centre

Solved my problem. Thank you.

**Comment by baptx** [comment]
@tzcrawford I got the issue with the PinePhone too, Waydroid did not use the whole height.
For Phosh on Mobian 13, I fixed the issue with the following commands after starting Waydroid (based on https://www.reddit.com/r/linuxquestions/comments/10e7uyw/how_to_start_waydroid_on_vertical_mode/):
`waydroid prop set persist.waydroid.width 360` (which is half of the PinePhone width resolution 720x1440)
`waydroid prop set persist.waydroid.height 675`
For an older version of Phosh on Mobian 12, I had to use a height of 650 because the bottom bar was larger.
To see the changes, you have to stop Waydroid for example with the command `sudo killall waydroid` and start Waydroid again.
