### ISSUE TITLE
Waydroid does not detect new images available on sourceforge

### ISSUE THREAD

**Issue by HanoJing** [waydroid/waydroid#827]
**Describe the bug**
As above, somehow when doing `waydroid upgrade` or `waydroid init` it pulls `0318` images when it should pull `0325` images.

**General information (please complete the following information):**
 - Waydroid tools Version: 1.3.4
 - Waydroid Images Version: latest `20230325` images

**Desktop (please complete the following information):**
 - OS: Void Linux ARM64
 - Motherboard: SolidRun HoneyComb LX2K
 - CPU: NXP LayerScape LX2160A Cortex-A72 ARM
 - GPU: AMD Radeon RX580
 - Kernel version: 6.1.3+
 - Host mesa version: 22.3.5
 - Desktop: Hyprland

**Additional context**
Might be an issue with sourceforge and `ota.waydro.id` being out of sync.

**Logs (please upload as file)**
 Not applicable in my case.

**Comment by cniw** [comment]
> Might be an issue with sourceforge and `ota.waydro.id` being out of sync.

yeah, there is still no new commits since March 18 2023 at https://github.com/waydroid/OTA/commits @betaxab please update it

**Comment by aleasto** [comment]
Two things happened here:
* [Github changed their RSA key](https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/) so the build server failed to push commits to waydroid/OTA.git
* The builds are broken because some of our patches needed rebasing after updates upstream

So we will not be publishing these builds to OTA.
In a way we got quite lucky!
