### ISSUE TITLE
Waydroid got removed after upgrading to Ubuntu 23.04

### ISSUE THREAD

**Issue by svta-7125** [waydroid/waydroid#858]
After updating to Lunar Lobster, all my waydroid shortcuts and apps disappeared. However my disk didn't lose any data that means the main android image is still there. When i try to reinstall waydroid i get this error:
![image](https://user-images.githubusercontent.com/117646988/233696836-faa53081-ff50-425d-aba9-8447831fb7dc.png)
Is it that python isn't supported yet on 23.04?

**Comment by cniw** [comment]
> Is it that python isn't supported yet on 23.04?

waydroid packages was build again python version depend on each ubuntu version.

the dependencies issue that make you can't install waydroid packages because your waydroid repo (`/etc/apt/sources.list.d/waydroid.list`) still using/contain repo config for the previous ubuntu version.
so before you can re-install the waydroid packages, you need to re-assign the waydroid repo with the correct version for your current ubuntu and then update the repo.

```bash
curl https://repo.waydro.id | sudo bash
sudo apt install waydroid -y
```
