### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by ROCKET1-1** [waydroid/waydroid#870]
Hi!
is it possible to use a proxy for the application or container to work?
if there is how to do it?

**Comment by ROCKET1-1** [comment]
> 

Thanks you!!!

**Comment by selurvedu** [comment]
FYI, to add a system CA certificate to allow TLS/SSL traffic inspection:

1. Find out the hash of the certificate subject name using the older algorithm as used by OpenSSL before version 1.0.0:
```shell
$ openssl x509 -subject_hash_old -in my-ca-cert.pem | head -1
13acab12
```
2. Create the `/system/etc/security/cacerts/` directory on the overlay FS:
```shell
$ sudo mkdir /var/lib/waydroid/overlay/system/etc/security/ /var/lib/waydroid/overlay/system/etc/security/cacerts/
```
3. Copy the certificate, renaming it to the hash from step 1, with `.0` appended:
```shell
$ sudo cp my-ca-cert.pem /var/lib/waydroid/overlay/system/etc/security/cacerts/13acab12.0
```

This works quite well with some applications I tried, including web browsers, and with HTTPS proxies such as mitmproxy, Burp, Fiddler, Charles, etc.

At first, I installed it as a user certificate, as described [here](https://httptoolkit.com/blog/android-11-trust-ca-certificates/#whats-changed), but it wasn't enough – it only worked in a browser, but not in other apps.

**Comment by selurvedu** [comment]
To unset the proxy, use this:
```shell
$ adb shell settings delete global http_proxy
$ adb shell settings delete global global_http_proxy_host
$ adb shell settings delete global global_http_proxy_port
```
This requires rebooting the device or, in case of Waydroid, restarting the session.

To unset the proxy without restarting Waydroid, use:
```
$ adb shell settings put global http_proxy :0
```

**Comment by VoLaNg** [comment]
Thanks @selurvedu, your comments was very helpful

In addition, don't forget to call: `sudo chmod 644 /var/lib/waydroid/overlay/system/etc/security/cacerts/<cert_hash.0>` to give it `-rw-r--r--` and restart waydroid session.

**Comment by selurvedu** [comment]
@houdinihacker thanks for the tip, I added that to my comment.

**Comment by cyfex** [comment]
> use adb.
> 
> ```
> adb shell settings put global http_proxy "192.168.240.1:7890"  
> ```

When I executed this command, it prompted:
```
Error while accessing settings provider
java.lang.NullPointerException: Attempt to invoke interface method 'android.app.IActivityManager$ContentProviderHolder android.app.IActivityManager.getContentProviderExternal(java.lang.String, int, android.os.IBinder)' on a null object reference
	at com.android.commands.settings.SettingsCmd.run(SettingsCmd.java:148)
	at com.android.commands.settings.SettingsCmd.main(SettingsCmd.java:63)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
```

Any idea?

**Comment by baptx** [comment]
@selurvedu Thanks, I was doing it wrong previously by using `sudo waydroid shell` and got the error "Read-only file system" when trying to copy the file directly in `/system/etc/security/cacerts/`.
For information, I did not have the folders `system/etc/security/cacerts/` in `/var/lib/waydroid/overlay/` so the easiest way to create all necessary folders is with this command:
`sudo mkdir -p /var/lib/waydroid/overlay/system/etc/security/cacerts`

**Comment by selurvedu** [comment]
@baptx the command I wrote in my comment should cover it too:
```
$ sudo mkdir /var/lib/waydroid/overlay/system/etc/security/ /var/lib/waydroid/overlay/system/etc/security/cacerts/
```
This will fail if `/var/lib/waydroid/overlay/system/etc/` does not exist yet.

`mkdir -p`, on the other hand, will always create the directory structure, even if `/var/lib/waydroid/overlay/system/etc/` or any parent directory (`/var/lib/waydroid/overlay/system/`, or `/var/lib/waydroid/overlay/`, or `/var/lib/waydroid/`) do not exist. That's why I used that command instead of `mkdir -p`, it should fail if the parent directories don't exist for whatever reason. It is to avoid creating the directory structure in a wrong place.

**Comment by baptx** [comment]
@selurvedu it did not cover it in my case because I meant all these directories did not exist in `/var/lib/waydroid/overlay`: `system` / `etc` / `security` / `cacerts`.

**Comment by selurvedu** [comment]
@baptx Interesting. There were other files and directories under `system/etc/` on my installation, but I suppose they may not exist until some program is executed, or if a user wants to install the certificate before running Waydroid for the first time. I updated the comment accordingly.

**Comment by billbeans** [comment]
I tried setting my proxy with the adb shell command listed above and it didn't work. I didn't even have adb at first, I had to install it through apt. My proxy also requires authentication so I added it in the format [user]:[pass]@[ip]:[port]. Waydroid was shut down when I did this. Not sure what the problem is, it's still using my home connection and not the proxy

**Comment by billbeans** [comment]
Attempting to use this guide but I don't have a network interface called waydroid0:

https://julien.duponchelle.info/android/use-proxy-with-waydroid

**Comment by billbeans** [comment]
Forget, I just used an app from GAPPS called SuperProxy and entered my proxy's information. Visiting whatsmyip.com yields my proxy's address, so I guess that works.

**Comment by Flashwalker** [comment]
> use adb.
> 
> ```
> adb shell settings put global http_proxy "192.168.240.1:7890"  
> ```

What's the point of using it?
You should up the proxy binded on 192.168.240.1:7890 ?

**Comment by ayasa520** [comment]
> What's the point of using it? You should up the proxy binded at 192.168.240.1:7890 on the host?

Clash is a proxy software, and its default port is 7890.
`192.168.240.1` is the IP address of the host machine (this is fixed in Waydroid).
This command allows Waydroid to use the proxy running on the host.

**Comment by baptx** [comment]
With Waydroid (Android 13), I can see mitmproxy enabled in the system CA certificates and can intercept HTTPS traffic of apps that don't have certificate pinning but it cannot intercept traffic in web views. When trying on the web browsers installed (Browser, Chrome, Firefox), it only works with Chrome and Firefox after accepting a warning but accepting this warning and changing the default web browser does not fix the issue for apps using the web view.
When testing with Android-x86 (Android 9) on virt-manager, the web browsers also display a warning but it is possible to intercept HTTPS traffic of the web view in apps.
Does someone else have this problem or a solution? You can try for example with an open source app like Aptoide by trying to log in with the "Connect with Google" button and monitoring traffic (using the old version https://github.com/Aptoide/aptoide-client-v8/releases/tag/v9.22.5.3(12060) since new versions don't seem to have the login feature anymore).
