### ISSUE TITLE
[QUESTION] There is a bar on the top of the app when launch it by adb command

### ISSUE THREAD

**Issue by stormyyd** [waydroid/waydroid#883]
**UPDATE**

It looks like the bar was introduced by [boringdroid](https://boringdroid.github.io/).

I managed to remove it by setting props, but I couldn't find a way to achieve that. Maybe it must be removed by editing the source code and rebuilding the image. Well, I gave it up.

**Description**

When I use adb to launch an app like this:

```bash
adb shell monkey -p com.android.settings -c android.intent.category.LAUNCHER --pct-syskeys 0 1
```

There will be a bar on the top of the app I launched. It has a **Back** button on the left side, and **Min** **Max** **Close** button on the right side. Just like the title bar of a Windows application. If I run it by clicking the app logo in the Launcher, the bar will not show up.

**Screenshot (The bar i descripted is marked by a red rectangle)**

![image](https://user-images.githubusercontent.com/4938213/236200951-7647ce93-ec31-41c5-9093-bce2fe7c212f.png)

![image](https://user-images.githubusercontent.com/4938213/236200968-37caeb8b-d0e3-4250-88b5-ca1b0a6d3605.png)

**General information**
 - Waydroid tools Version: `1.4.0`
 - Waydroid Images Version: `VANILLA 20230422`

**Desktop**
 - OS: Arch Linux
 - GPU: AMD Radeon™ RX Vega 7 (AMD Ryzen™ 5 5600G Built-in GPU)
 - Kernel version: Linux-Zen 6.2.13
 - Host mesa version: `23.0.3`
 - Desktop: **sway** with headless setting and **wayvnc**

**Question**

What exactly is it? I haven't seen it before on any Android devices. Is there a way to remove it?

**Comment by acvlwe** [comment]
i want it remove too, it this resolve?how?

**Comment by stormyyd** [comment]
> i want it remove too, it this resolve?how?

@acvlwe Nope, but if all you need is to run an Android OS on your x86 system, I would personally recommend you trying [redroid](https://github.com/remote-android/redroid-doc) to instead, which works fine for me :)

**Comment by acvlwe** [comment]
> > i want it remove too, it this resolve?how?
> 
> @acvlwe Nope, but if all you need is to run an Android OS on your x86 system, I would personally recommend you trying [redroid](https://github.com/remote-android/redroid-doc) to instead, which works fine for me :)

yes,i try that before and some binder(kernel features) issue i cannot fix, didnt work.

**Comment by dreadfulman** [comment]
There is a work around for this using adb Activity Manager (AM). You have to specify the windowingMode as such:
`adb shell am start --windowingMode 4 com.package.name/.activity_name`

Here's an example using the calculator app:
`adb shell am start --windowingMode 4 com.android.calculator2/.Calculator`
This should launch the android Calculator app in full screen without the top bar.

This is part of the multiwindow feature in Android which is enabled by default on Android 7.0 and up. Changing the integer value will launch the apps in different window modes. Based on my testing on Waydroid this what I found:

`--windowingMode 0` and `1` - launches apps in BoringDroid windows
`--windowingMode 2` - Picture-in-Picture (PIP) mode
`--windowingMode 3` - Split-screen mode
`--windowingMode 4` - Full-screen mode without top bar

By default AM and Monkey evidently launch apps in `--windowingMode 0` or `1`, which is bound to BoringDroid on Waydroid. Idk if it's possible to change this behaviour. But atleast with AM you can specify. Monkey doesn't have such capability afaik, which is unfortunate since with AM you need to specify the name of the LAUNCHER activity of the app as well which can be a hassle.

Credits to FalconSN in the Waydroid IRC channel on Matrix for letting me know about this workaround.

BTW you mentioned managing to remove it but setting props. Can you elaborate on that?

**Comment by stormyyd** [comment]
@fuwaai OMG, thank you! Your workaround works prefectly!

In fact, I'm not familiar with Android, which led me to believe that the top bar was introduced by the BoringDroid component rather than Android itself. So at the first beginning, I think maybe there is a props ([Waydroid Prop Options](https://docs.waydro.id/usage/waydroid-prop-options)), build flag or anything like that could control the behaviour of the top bar, or delete the BoringDroid component to make the top bar disappear completely. But as I mentioned before, I cannot find such thing so I gave it up and go play with [redroid](https://github.com/remote-android/redroid-doc).

So there is no further investigation on that, sorry for that.

And finally, I want to express my gratitude to you. According to the number of times this issue has been referenced and the project related to those issues, the information you provided had really helped a lot of people, thank you so much!
