### ISSUE TITLE
Copy from host, paste on android

### ISSUE THREAD

**Issue by yajo** [waydroid/waydroid#892]
**Is your feature request related to a problem? Please describe.**
I want to write emojis. But my keyboard has no emojis. And on Waydroid I hide the on-screen keyboard because othewise it eats all my space.

**Describe the solution you'd like**
Install [one emoji app on host](https://flathub.org/es/apps/org.gnome.Characters), copy from there, paste on Android.

**Describe alternatives you've considered**
Displaying on-screen keyboard. Not nice.

Installing emoji app on Android. Not nice.

Using <kbd>Super</kbd>+<kbd>.</kbd> combination, which works on other GTK apps on GNOME to input emojis. Not working.

Copying from host into Android. Not working. Thus, this issue 😄 

**Additional context**
I guess the feature would be quite useful on many other contexts.

**Comment by aleasto** [comment]
It is already supported. Install pyclip and wl-clipboard

**Comment by tgm-git** [comment]
@aleasto I am running Waydroid on a Librem 5 and have installed pyclip and wl-clipboard on the phone. I can copy and paste to and from phone by manually calling `wl-copy` or `wl-paste`, but my clipboard is not automatically synched between the host and the android container.

Am I missing something or is this the expected behaviour?

**Comment by musjj** [comment]
Same here, not sure what I'm missing.

@tgm-git Did you manage to solve this?

**Comment by tgm-git** [comment]
@musjj I did not. I ended up switching to a LineageOS device as my daily driver instead of using Librem 5 and Waydroid.
