### ISSUE TITLE
https://repo.waydro.id certificate broken

### ISSUE THREAD

**Issue by Bob0111** [waydroid/waydroid#910]
The apt package manager cannot download files from the repo due to the certification error. And I try to visit the link through browser, it tells me that Firefox does not trust this site because it uses a certificate that is not valid for repo.waydro.id. The certificate is only valid for oldpc.mrcyjanek.net. And the error code is SSL_ERROR_BAD_CERT_DOMAIN.

**Comment by arikyo07** [comment]
Probably @mrcyjanek's server.
The server's settings are incorrect and it is providing the wrong certificate.
I hope this issue is resolved soon.
As of now, disabling TLS certificate verification by following https://serverfault.com/a/340889 is the only workaround, but I do not recommend doing this for security reasons.

**Comment by MrCyjaneK** [comment]
The issue is now resolved, certbot decided to hang on one domain which caused nginx to not restart.. It is working fine now.
