### ISSUE TITLE
XDG Session not "wayland" (but it is)

### ISSUE THREAD

**Issue by BIGJ541** [waydroid/waydroid#93]
Running Ubuntu 21.04 Gnome 40

root@bigj541-desktop:/home/bigj541# waydroid session start
[03:29:43] XDG Session is not "wayland"
[03:29:45] Failed to start Clipboard manager service, check logs

bigj541@bigj541-desktop:~$ echo $XDG_SESSION_TYPE
wayland
bigj541@bigj541-desktop:~$ env | grep -i wayland
XDG_SESSION_TYPE=wayland
XAUTHORITY=/run/user/1000/.mutter-Xwaylandauth.F2JZ90
WAYLAND_DISPLAY=wayland-0
bigj541@bigj541-desktop:~$

**Comment by sigmaSd** [comment]
You are running waydroid session start as root which doesnt have the same env.

**Comment by Id2ndR** [comment]
To be more specific, `waydroid session start` command should be run in the user session.

**Comment by Etaash-mathamsetty** [comment]
I am having this issue as a regular user when using mutter and trying to run a session with only waydroid

**Comment by Etaash-mathamsetty** [comment]
fixed now

**Comment by cjcj5243** [comment]
@Etaash-mathamsetty Can u tell me How to solve it? I am having the same issue……

**Comment by Etaash-mathamsetty** [comment]
Idk how to fix it lol, it fixed itself

**Comment by cniw** [comment]
@cjcj5243 The problem was explained above by @sigmaSd

    You are running waydroid session start as root which doesnt have the same env.

So it should be fine/works if you running `waydroid session start` with regular user (indicated with `$` sign in your terminal shell) **not** with root user (indicated with `#` sign in your terminal shell) **nor** `sudo`/`doas` prefix.

Then if you're still had same issue that mean you're not in/use wayland session, logout and select wayland session in session option at login screen before you're re-login to desktop
