### ISSUE TITLE
Some apps crash suddenly while running

### ISSUE THREAD

**Issue by MinGW32-2006** [waydroid/waydroid#971]
**Describe the bug**
I run arknights on waydroid. It seems to work fine, but it crashes during battles, in the operators page, etc. I'd like to ask how I can get the game run stably on waydroid.

**Screenshots**
None, since it crashes instantly.

**General information (please complete the following information):**
 - Waydroid tools Version: 1.4.1
 - Waydroid Images Version: 20230422 VANILLA MAINLINE

**Desktop (please complete the following information):**
 - OS: Fedora 36
 - GPU: Intel HD Graphics 3000
 - Kernel version: 6.2.15
 - Host mesa version: 22.1.7
 - Desktop: GNOME 42.9

**Additional context**
The problem happens especially frequently when I scroll the game UI "violently".

**Logs (please upload as file)**
file:///home/fedora/%E4%B8%8B%E8%BD%BD/waydroid-logs/waydroid.prop
file:///home/fedora/%E4%B8%8B%E8%BD%BD/waydroid-logs/waydroid.log
file:///home/fedora/%E4%B8%8B%E8%BD%BD/waydroid-logs/waydroid-logcat.log
file:///home/fedora/%E4%B8%8B%E8%BD%BD/waydroid-logs/dmesg.log

**Comment by MinGW32-2006** [comment]
Seems I failed to upload the logs.
[waydroid-logs.zip](https://github.com/waydroid/waydroid/files/11846652/waydroid-logs.zip)

**Comment by RaziFalah** [comment]
Your log files doesn't show errors, because there isn't really one. You have low computing resources and waydroid is a virtualization software so you end up with less resources.
It crashes specially when you're in battles proves that it's due to your specs. because in battles is when games take the most resources.

**Comment by MinGW32-2006** [comment]
However I noticed that there was still 40% memory vacant and only 30% cpu usage. I'm unable to monitor my iGPU since it is Sandy Bridge (HD 3000). So I can't understand why "I have low computing resources".

**Comment by RaziFalah** [comment]
That's why i said "waydroid is a virtualization software so you end up with even less resources", There's a limit on how much waydroid is allowed to consume. i think it's dynamic meaning it scans your computer availability and choose how much to consume regardingly. 

If you manage to manually edit this configuration it might help, but also it might cause other services and softwares in your computer to crash or misbehave. Also waydroid doesn't specify how to do that so you will have to figure that out yourself, if it's even possible without ending up making your own project.

**Comment by MinGW32-2006** [comment]
I know. But low computing resources causes in low frame rate. I'm still wondering why waydroid will crash even when there is almost no pressure on the cpu, memory, etc. It should not CRASH.

**Comment by MinGW32-2006** [comment]
I think waydroid will run slower on older PCs. But why does it crash?

**Comment by RaziFalah** [comment]
If you didn't face any graphical failures for example frame drops, low frame rate or unresponsivity. Then it's possible that waydroid is to blame.

I've recently came across issues which I think is similar to yours for examples apps like tiktok and instgram seems to be working fine until they suddenly fail.

I opened an issue here also I tried to figure out the cause but no luck so far. I'm assuming it's because of bad communications between waydroid and the host. This issues happens also on anbox, which is what waydroid is built on.

In the meantime There's no fix for this issue, it would be challenging to create proper ways to communicate with different machines.

**Comment by MinGW32-2006** [comment]
I also tried xDroid, a similar container to waydroid and anbox, and it works really well, without any errors. The problem should be probably caused by waydroid (or anbox) itself. My computer hardware may have nothing to do with the problem. (xDroid violates the open source license. I hope you won't be angry.)

**Comment by RaziFalah** [comment]
Oh no do not worry, there's no license on earth i didn't end up violating

**Comment by MinGW32-2006** [comment]
So why can xDroid work fine? It's also based on anbox.

**Comment by RaziFalah** [comment]
I would assume that waydroid includes some functionalities that causes some sort of graphical failure, but given the fact that anbox have this issues as well, i'm thinking maybe xDroid fixed something in anbox itself or just dis-clouded some functionalities.

**Comment by MinGW32-2006** [comment]
I tested this game using bluestacks on windows. Seems I have an overloaded gpu... I got blue screen on windows if I open both the game and a video website. But on waydroid I got a crash even if I have only the game running. So waydroid requires more resources than an Android emulator? Sounds strange.

**Comment by MinGW32-2006** [comment]
And I barely meet blue screen on android emulators on Windows.

**Comment by MinGW32-2006** [comment]
And I barely meet blue screen on android emulators on Windows.

**Comment by Quackdoc** [comment]
how does it crash? does the entire waydroid instance crash? or does the app itself crash? are you running in waydroid show-full-ui?

**Comment by Quackdoc** [comment]
also if you can run `logcat -c` before running arknights, then run logcat immediately after it crashes that can help too

**Comment by MinGW32-2006** [comment]
I run arknights in multi window mode. When it crashes the waydroid container seems fine. It is still running. Fake touch doesn't help, and causes more problems since arknights have original mouse support. I haven't tried fake WiFi but this problem may have nothing to do with network I think.

**Comment by MinGW32-2006** [comment]
Update: The game run well. But it crashes on login. The waydroid container is fine. The problem is probably caused by my computer iGPU.

**Comment by TTsdzb** [comment]
I think I'm having the same situation here. I've opened a [discussion](https://github.com/waydroid/waydroid/discussions/1847) about that.
