### ISSUE TITLE
THIS REPOSITORY IS A MINER IN THE BACKGROUND, DON'T USE REPOSITORY!

### ISSUE THREAD

**Issue by andres-info** [waydroid/waydroid#98]
THIS REPOSITORY IS A MINER IN THE BACKGROUND, DON'T USE REPOSITORY!
![xmrig](https://user-images.githubusercontent.com/41297392/134793944-85c42519-f00f-4176-ae12-545639b59bbd.jpeg)

**Comment by erfanoabdi** [comment]
oof

**Comment by andres-info** [comment]
https://repo.waydro.id/?fbclid=IwAR0bNLBZXuLCOREmui0BaGtKu6uB_nw7ifnWs7uHwJ_R2optnaKB-DfYQsg

**Comment by erfanoabdi** [comment]
this is common repo with @MrCyjaneK personal repo,
waydroid packages are completely separate.
beside that, waydroid tool is completely payton and you can extract deb files to look inside 
Please don’t spread false information, there's no miner

**Comment by andres-info** [comment]
i clone this repository and i executed this container and docker use up more memory ram, dont' view process xmrig in second plane but in the router i found internet outlet to xmrig

**Comment by erfanoabdi** [comment]
you might have to check again, there's no miner

**Comment by MrCyjaneK** [comment]
Hey @andres-info, there is no miner. To be clear:
 - There *is* a miner in files, but it's in a different repo. You can't install it from the waydroid repo (unless you mess with the source list...)
 - Even if you manage to install the xmrig from my repo, you will have a xmrig binary, which do nothing by default, unless you run it.
 - If waydroid would install xmrig, you would see that its being downloaded from apt. And your pc would be unusable, and locked at 100%cpu on all cores.

This mess in here happened because I was quite lazy when preparing the repo, and the .deb files are shared in both mine and waydroid repo, but the lists in mine and waydroid repo are different - you can't install waydroid from mine repo and you can't install xmrig from waydroid repo.

Also I'm working on a new repo which is not generated by bash script.. so it will be even more clear that waydroid and my repo are separate..
